// <auto-generated />
using System;
using Ayapos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ayapos.Api.Migrations
{
    [DbContext(typeof(AyaposDbContext))]
    partial class AyaposDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ayapos.Api.Data.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("scheduled");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex(new[] { "StaffId", "StartAt" }, "IX_Appointments_Staff_StartAt");

                    b.HasIndex(new[] { "StartAt" }, "IX_Appointments_StartAt");

                    b.HasIndex(new[] { "TenantId", "BranchId", "StartAt" }, "IX_Appointments_Tenant_Branch_StartAt");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.AppointmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("AED")
                        .IsFixedLength();

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AppointmentId" }, "IX_AppointmentItems_AppointmentId");

                    b.ToTable("AppointmentItems");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "Code" }, "UQ_Branches_Tenant_Code")
                        .IsUnique();

                    b.HasIndex(new[] { "TenantId", "Id" }, "UQ_Branches_Tenant_Id")
                        .IsUnique();

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.BranchExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("AED")
                        .IsFixedLength();

                    b.Property<DateTime>("ExpenseDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime?>("PaidAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("cash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("draft");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "BranchId", "ExpenseDate" }, "IX_BranchExpenses_Tenant_Branch_Date");

                    b.ToTable("BranchExpenses");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.BranchSetting", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowInvoiceDiscount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowLineDiscount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("AutoPrintReceiptAfterPayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("CompanyAddress")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("CompanyLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("CompanyPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CompanyTaxNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("MaxCashierDiscountPct")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("ReceiptFooterNote")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("ReceiptHeaderLine1")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ReceiptHeaderLine2")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ReceiptTitle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("Sales Receipt");

                    b.Property<bool>("RequireManagerForPriceOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowBranchNameOnReceipt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowCustomerNameOnReceipt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowPaymentHistoryOnReceipt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TenantId", "BranchId");

                    b.ToTable("BranchSettings");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.BranchUserAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "BranchId");

                    b.HasIndex("BranchId");

                    b.HasIndex(new[] { "TenantId", "BranchId" }, "IX_BranchUserAssignments_Tenant_Branch");

                    b.ToTable("BranchUserAssignments", (string)null);
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.CashierSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActualCashCents")
                        .HasColumnType("integer");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DifferenceCents")
                        .HasColumnType("integer");

                    b.Property<string>("DiscrepancyReason")
                        .HasColumnType("text");

                    b.Property<int>("ExpectedCashCents")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpeningCashCents")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalCardCents")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCashCents")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRefundCents")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTransferCents")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CashierSessions");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FullName" }, "IX_Customers_FullName");

                    b.HasIndex(new[] { "Phone" }, "IX_Customers_Phone");

                    b.HasIndex(new[] { "TenantId" }, "IX_Customers_TenantId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.DocumentUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("OTHER");

                    b.Property<string>("ExtractedFieldsJson")
                        .HasColumnType("text");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text");

                    b.Property<string>("ReviewedFieldsJson")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("LanguageHint")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("auto");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "BranchId", "Status" }, "IX_DocumentUploads_Tenant_Branch_Status");

                    b.ToTable("DocumentUploads");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.DocumentAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentUploadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentUploadId", "IX_DocumentAuditLogs_DocumentUploadId");

                    b.ToTable("DocumentAuditLogs");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.CustomerLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedInvoiceId");

                    b.HasIndex(new[] { "TenantId", "CustomerId" }, "IX_CustomerLicenses_Tenant_Customer");

                    b.ToTable("CustomerLicenses");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.InventoryMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("MoveType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex(new[] { "TenantId", "BranchId", "CreatedAt" }, "IX_InvMoves_Tenant_Branch_CreatedAt");

                    b.HasIndex(new[] { "ProductId", "CreatedAt" }, "IX_InventoryMoves_Product_Time")
                        .IsDescending(false, true);

                    b.ToTable("InventoryMoves");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("DiscountCents")
                        .HasColumnType("integer");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("InvoiceNo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ISSUED");

                    b.Property<int>("SubtotalCents")
                        .HasColumnType("integer");

                    b.Property<int>("TaxCents")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalCents")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex(new[] { "TenantId", "BranchId", "CreatedAt" }, "IX_Invoices_Tenant_Branch_CreatedAt");

                    b.HasIndex(new[] { "TenantId", "BranchId", "InvoiceNo" }, "UQ_Invoices_Tenant_Branch_InvoiceNo")
                        .IsUnique();

                    b.HasIndex(new[] { "TenantId", "BranchId", "InvoiceNo" }, "UQ_Invoices_Tenant_Branch_No")
                        .IsUnique();

                    b.HasIndex(new[] { "TenantId", "Id" }, "UQ_Invoices_Tenant_Id")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<int>("DiscountCents")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DiscountPct")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("DiscountReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("LineTotalCents")
                        .HasColumnType("integer");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("PriceOverrideCents")
                        .HasColumnType("integer");

                    b.Property<string>("PriceOverrideReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnitPriceCents")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "InvoiceId" }, "IX_InvoiceItems_InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.InvoiceSequence", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<int>("NextNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TenantId", "BranchId");

                    b.HasIndex("BranchId");

                    b.ToTable("InvoiceSequences");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("MaxDevices")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LicenseKey" }, "UX_Licenses_LicenseKey")
                        .IsUnique();

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.LicenseActivation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ActivatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LicenseId", "LastSeenAt" }, "IX_LA_License_LastSeen")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "LicenseId", "DeviceId" }, "UX_LA_License_Device")
                        .IsUnique();

                    b.ToTable("LicenseActivations");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.ManagerApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApprovalType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("ApprovedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "BranchId", "RefType", "RefId", "ApprovedAt" }, "IX_ManagerApprovals_Ref")
                        .IsDescending(false, false, false, false, true);

                    b.ToTable("ManagerApprovals");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Method")
                        .HasMaxLength(10)
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaidAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "InvoiceId");

                    b.HasIndex(new[] { "InvoiceId" }, "IX_Payments_InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Barcode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostPrice")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("AED")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NameAr")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("ReorderPoint")
                        .HasColumnType("integer");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TrackInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pcs");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsActive" }, "IX_Products_Active");

                    b.HasIndex(new[] { "Barcode" }, "IX_Products_Barcode");

                    b.HasIndex(new[] { "TenantId", "BranchId" }, "IX_Products_Tenant_Branch");

                    b.HasIndex(new[] { "TenantId", "BranchId", "Barcode" }, "UQ_Products_Tenant_Branch_Barcode")
                        .IsUnique()
                        .HasFilter("\"Barcode\" IS NOT NULL");

                    b.HasIndex(new[] { "TenantId", "BranchId", "Sku" }, "UQ_Products_Tenant_Branch_Sku")
                        .IsUnique()
                        .HasFilter("\"Sku\" IS NOT NULL");

                    b.HasIndex(new[] { "Sku" }, "UX_Products_Sku_NotNull")
                        .IsUnique()
                        .HasFilter("\"Sku\" IS NOT NULL");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("PriceCents")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "BranchId", "ProductId", "IsActive" }, "IX_ProductPrices_Lookup");

                    b.HasIndex(new[] { "TenantId", "BranchId", "ProductId" }, "UX_ProductPrices_Active")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("ProductPrices");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.ProductStockSnapshot", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<int>("QtyOnHand")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProductId");

                    b.HasIndex(new[] { "TenantId", "BranchId", "ProductId" }, "UQ_Stock_Tenant_Branch_Product")
                        .IsUnique();

                    b.ToTable("ProductStockSnapshot", (string)null);
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefundedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DurationMin")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NameAr")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsActive" }, "IX_Services_Active");

                    b.HasIndex(new[] { "TenantId", "BranchId" }, "IX_Services_Tenant_Branch");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.ServicePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("PriceCents")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex(new[] { "TenantId", "BranchId", "IsActive" }, "IX_ServicePrices_Branch_Active");

                    b.HasIndex(new[] { "TenantId", "BranchId", "ServiceId" }, "UQ_ServicePrices_Tenant_Branch_Service")
                        .IsUnique();

                    b.ToTable("ServicePrices");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AppointmentColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("BaseSalary")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("DeductionPerAbsentDay")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal?>("DeductionPerLateMinute")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("EmploymentType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("employee");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("HireDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBookableForAppointments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JobTitle")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("SalaryType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("monthly");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TrackAttendance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("WeeklyOffDays")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("LinkedUserId");

                    b.HasIndex(new[] { "FullName" }, "IX_Staff_FullName");

                    b.HasIndex(new[] { "TenantId", "BranchId", "IsActive" }, "IX_Staff_Tenant_Branch_Active");

                    b.HasIndex(new[] { "TenantId", "BranchId", "IsBookableForAppointments" }, "IX_Staff_Tenant_Branch_Bookable");

                    b.HasIndex(new[] { "TenantId", "BranchId", "EmployeeCode" }, "UQ_Staff_Tenant_Branch_EmployeeCode")
                        .IsUnique()
                        .HasFilter("\"EmployeeCode\" IS NOT NULL");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.StaffAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AttendanceDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckInAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<DateTime?>("CheckOutAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DeductionAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("LateMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("present");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("WorkedMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("StaffId");

                    b.HasIndex(new[] { "TenantId", "BranchId", "AttendanceDate" }, "IX_StaffAttendances_Branch_Date");

                    b.HasIndex(new[] { "TenantId", "BranchId", "StaffId", "AttendanceDate" }, "UQ_StaffAttendances_Staff_Date")
                        .IsUnique();

                    b.ToTable("StaffAttendances");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.StaffDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<string>("FileName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex(new[] { "TenantId", "BranchId", "StaffId" }, "IX_StaffDocuments_Staff");

                    b.ToTable("StaffDocuments");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.StaffLeave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("EndDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("approved");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex(new[] { "TenantId", "BranchId", "StartDate" }, "IX_StaffLeaves_Branch_StartDate");

                    b.HasIndex(new[] { "TenantId", "BranchId", "StaffId" }, "IX_StaffLeaves_Staff");

                    b.ToTable("StaffLeaves");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.StaffShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("GraceMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("WeeklyPattern")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex(new[] { "TenantId", "BranchId", "StaffId", "IsActive" }, "IX_StaffShifts_Staff_Active");

                    b.ToTable("StaffShifts");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("LicenseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicensePlan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("MONTHLY");

                    b.Property<DateTime>("LicenseStartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LicenseStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<int>("MaxUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Slug" }, "UQ_Tenants_Slug")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LicenseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicensePlan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("MONTHLY");

                    b.Property<DateTime>("LicenseStartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LicenseStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PermissionsJson")
                        .HasColumnType("text");

                    b.Property<string>("PinHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Username" }, "IX_Users_Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.UserPin", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Algo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("SHA2_256");

                    b.Property<int>("Iterations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<byte[]>("PinHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PinSalt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "TenantId")
                        .HasName("PK_UserPins_UserTenant");

                    b.ToTable("UserPins");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.UserPinsHistory", b =>
                {
                    b.Property<string>("Algo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Iterations")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PinHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PinSalt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTime>("SysEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SysStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex(new[] { "SysEndTime", "SysStartTime" }, "ix_UserPinsHistory");

                    b.ToTable("UserPinsHistory", (string)null);
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.vw_ProductActivePrice", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<int>("PriceCents")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.ToTable((string)null);

                    b.ToView("vw_ProductActivePrices", (string)null);
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Appointment", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.User", "CreatedByUser")
                        .WithMany("Appointments")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_Appointments_User");

                    b.HasOne("Ayapos.Api.Data.Entities.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Appointments_Customer");

                    b.HasOne("Ayapos.Api.Data.Entities.Staff", "Staff")
                        .WithMany("Appointments")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK_Appointments_Staff");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.AppointmentItem", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Appointment", "Appointment")
                        .WithMany("AppointmentItems")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AppointmentItems_Appointment");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Branch", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Tenant", "Tenant")
                        .WithMany("Branches")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Branches_Tenants");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.BranchSetting", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Branch", "Branch")
                        .WithOne("BranchSetting")
                        .HasForeignKey("Ayapos.Api.Data.Entities.BranchSetting", "TenantId", "BranchId")
                        .HasPrincipalKey("Ayapos.Api.Data.Entities.Branch", "TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_BranchSettings_Branches");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.BranchUserAssignment", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Branch", "Branch")
                        .WithMany("BranchUserAssignments")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_BranchUserAssignments_Branches");

                    b.HasOne("Ayapos.Api.Data.Entities.User", "User")
                        .WithMany("BranchUserAssignments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_BranchUserAssignments_Users");

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.CustomerLicense", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Invoice", "CreatedInvoice")
                        .WithMany("CustomerLicenses")
                        .HasForeignKey("CreatedInvoiceId")
                        .HasConstraintName("FK_CustomerLicenses_Invoices");

                    b.HasOne("Ayapos.Api.Data.Entities.Tenant", "Tenant")
                        .WithMany("CustomerLicenses")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_CustomerLicenses_Tenants");

                    b.Navigation("CreatedInvoice");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.InventoryMove", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.User", "CreatedByUser")
                        .WithMany("InventoryMoves")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_InventoryMoves_User");

                    b.HasOne("Ayapos.Api.Data.Entities.Product", "Product")
                        .WithMany("InventoryMoves")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_InventoryMoves_Product");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Invoice", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Branch", "Branch")
                        .WithMany("InvoiceBranches")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoices_Branches");

                    b.HasOne("Ayapos.Api.Data.Entities.Tenant", "Tenant")
                        .WithMany("Invoices")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoices_Tenants");

                    b.HasOne("Ayapos.Api.Data.Entities.Branch", "BranchNavigation")
                        .WithMany("InvoiceBranchNavigations")
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_Invoices_Branches_Tenant");

                    b.Navigation("Branch");

                    b.Navigation("BranchNavigation");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.InvoiceItem", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceItems_Invoices");

                    b.HasOne("Ayapos.Api.Data.Entities.Product", "Product")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_InvoiceItems_Products");

                    b.HasOne("Ayapos.Api.Data.Entities.Service", "Service")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_InvoiceItems_Services");

                    b.HasOne("Ayapos.Api.Data.Entities.Tenant", "Tenant")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceItems_Tenants");

                    b.Navigation("Invoice");

                    b.Navigation("Product");

                    b.Navigation("Service");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.InvoiceSequence", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Branch", "Branch")
                        .WithMany("InvoiceSequenceBranches")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceSequences_Branches");

                    b.HasOne("Ayapos.Api.Data.Entities.Tenant", "Tenant")
                        .WithMany("InvoiceSequences")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceSequences_Tenants");

                    b.HasOne("Ayapos.Api.Data.Entities.Branch", "BranchNavigation")
                        .WithOne("InvoiceSequenceBranchNavigation")
                        .HasForeignKey("Ayapos.Api.Data.Entities.InvoiceSequence", "TenantId", "BranchId")
                        .HasPrincipalKey("Ayapos.Api.Data.Entities.Branch", "TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceSequences_Branches_Tenant");

                    b.Navigation("Branch");

                    b.Navigation("BranchNavigation");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.LicenseActivation", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.License", "License")
                        .WithMany("LicenseActivations")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LA_License");

                    b.Navigation("License");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Payment", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Tenant", "Tenant")
                        .WithMany("Payments")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Tenants");

                    b.HasOne("Ayapos.Api.Data.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("TenantId", "InvoiceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Invoices_Tenant");

                    b.Navigation("Invoice");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Product", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Branch", "Branch")
                        .WithMany("Products")
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Branches_Tenant");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.ProductStockSnapshot", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Product", "Product")
                        .WithOne("ProductStockSnapshot")
                        .HasForeignKey("Ayapos.Api.Data.Entities.ProductStockSnapshot", "ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductStockSnapshot_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.ServicePrice", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Service", "Service")
                        .WithMany("ServicePrices")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_ServicePrices_Services");

                    b.HasOne("Ayapos.Api.Data.Entities.Tenant", "Tenant")
                        .WithMany("ServicePrices")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_ServicePrices_Tenants");

                    b.HasOne("Ayapos.Api.Data.Entities.Branch", "Branch")
                        .WithMany("ServicePrices")
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_ServicePrices_Branches_Tenant");

                    b.Navigation("Branch");

                    b.Navigation("Service");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Staff", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.User", "LinkedUser")
                        .WithMany("LinkedStaffMembers")
                        .HasForeignKey("LinkedUserId")
                        .HasConstraintName("FK_Staff_Users");

                    b.HasOne("Ayapos.Api.Data.Entities.Branch", "Branch")
                        .WithMany("StaffMembers")
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_Staff_Branches_Tenant");

                    b.Navigation("Branch");

                    b.Navigation("LinkedUser");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.StaffAttendance", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.StaffShift", "Shift")
                        .WithMany("Attendances")
                        .HasForeignKey("ShiftId")
                        .HasConstraintName("FK_StaffAttendances_StaffShifts");

                    b.HasOne("Ayapos.Api.Data.Entities.Staff", "Staff")
                        .WithMany("Attendances")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_StaffAttendances_Staff");

                    b.HasOne("Ayapos.Api.Data.Entities.Branch", "Branch")
                        .WithMany("StaffAttendances")
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_StaffAttendances_Branches_Tenant");

                    b.Navigation("Branch");

                    b.Navigation("Shift");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.StaffDocument", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Staff", "Staff")
                        .WithMany("Documents")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_StaffDocuments_Staff");

                    b.HasOne("Ayapos.Api.Data.Entities.Branch", "Branch")
                        .WithMany("StaffDocuments")
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_StaffDocuments_Branches_Tenant");

                    b.Navigation("Branch");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.StaffLeave", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Staff", "Staff")
                        .WithMany("Leaves")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_StaffLeaves_Staff");

                    b.HasOne("Ayapos.Api.Data.Entities.Branch", "Branch")
                        .WithMany("StaffLeaves")
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_StaffLeaves_Branches_Tenant");

                    b.Navigation("Branch");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.StaffShift", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.Staff", "Staff")
                        .WithMany("Shifts")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_StaffShifts_Staff");

                    b.HasOne("Ayapos.Api.Data.Entities.Branch", "Branch")
                        .WithMany("StaffShifts")
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_StaffShifts_Branches_Tenant");

                    b.Navigation("Branch");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.UserPin", b =>
                {
                    b.HasOne("Ayapos.Api.Data.Entities.User", "User")
                        .WithMany("UserPins")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserPins_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Appointment", b =>
                {
                    b.Navigation("AppointmentItems");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Branch", b =>
                {
                    b.Navigation("BranchSetting");

                    b.Navigation("BranchUserAssignments");

                    b.Navigation("InvoiceBranchNavigations");

                    b.Navigation("InvoiceBranches");

                    b.Navigation("InvoiceSequenceBranchNavigation");

                    b.Navigation("InvoiceSequenceBranches");

                    b.Navigation("Products");

                    b.Navigation("ServicePrices");

                    b.Navigation("StaffAttendances");

                    b.Navigation("StaffDocuments");

                    b.Navigation("StaffLeaves");

                    b.Navigation("StaffMembers");

                    b.Navigation("StaffShifts");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Customer", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Invoice", b =>
                {
                    b.Navigation("CustomerLicenses");

                    b.Navigation("InvoiceItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.License", b =>
                {
                    b.Navigation("LicenseActivations");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Product", b =>
                {
                    b.Navigation("InventoryMoves");

                    b.Navigation("InvoiceItems");

                    b.Navigation("ProductStockSnapshot");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Service", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("ServicePrices");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Staff", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Attendances");

                    b.Navigation("Documents");

                    b.Navigation("Leaves");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.StaffShift", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.Tenant", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("CustomerLicenses");

                    b.Navigation("InvoiceItems");

                    b.Navigation("InvoiceSequences");

                    b.Navigation("Invoices");

                    b.Navigation("Payments");

                    b.Navigation("ServicePrices");
                });

            modelBuilder.Entity("Ayapos.Api.Data.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BranchUserAssignments");

                    b.Navigation("InventoryMoves");

                    b.Navigation("LinkedStaffMembers");

                    b.Navigation("UserPins");
                });
#pragma warning restore 612, 618
        }
    }
}
